language: php
sudo: false

php:
 - 5.5
 - 5.6
 - 7.0

matrix:
  fast_finish: true

before_script:
  - wget https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
  - wget https://phar.phpunit.de/phpcpd.phar
  ## PHP Mess Detector
  - pear config-set preferred_state beta
  - printf "\n" | pecl install imagick
  - pear channel-discover pear.phpmd.org
  - pear channel-discover pear.pdepend.org
  - pear install --alldeps phpmd/PHP_PMD
  - phpenv rehash

script:
 - php phpcs.phar --encoding=utf-8 --extensions=php --standard=psr2 --ignore=vendor .
 - php phpcpd.phar --min-lines 25 --verbose --exclude vendor .
 - phpmd . text  codesize, controversial, design, naming, unusedcode
