<?php

namespace Maven\Bundle\MagentoBundle;

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

use Maven\Bundle\MagentoBundle\DependencyInjection\Compiler\TransportSoapPass;
use Maven\Bundle\MagentoBundle\DependencyInjection\MavenMagentoExtension;

use Maven\Bundle\MagentoBundle\DependencyInjection\Compiler\DeliveryHandlerPass;

/**
 * @package Maven\Bundle\MagentoBundle
 */
class MavenMagentoBundle extends Bundle
{
    /**
     * {@inheritdoc}
     */
    public function build(ContainerBuilder $container)
    {
        parent::build($container);

        $container->addCompilerPass(new DeliveryHandlerPass());
        $container->addCompilerPass(new TransportSoapPass());
    }

    /**
     * @return string
     */
    public function getParent()
    {
        return 'OroCRMMagentoBundle';
    }

    public function getContainerExtension()
    {
        return new MavenMagentoExtension(); // TODO: Change the autogenerated stub
    }
}
